In [1]:
import cv2

In [3]:
img = cv2.imread('C:/Users/Monika/Pictures/Camera Roll/Trapti.jpg')

In [4]:
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

In [5]:
img_flat = img.reshape((-1, 3))

In [6]:
img_flat.shape

(466200, 3)

In [7]:
import numpy as np

In [73]:
def distance(x1, x2):
    return np.sqrt(np.sum((x1-x2)**2, axis=1))

In [183]:
class KMeans:
    def __init__(self, X, k):
        self.k = k
        self.X = X
        self.centers = 255 * np.random.rand(self.k, 3)
        self.cluster = []
        
    def setCluster(self):
        cluster = []
        no_of_datapoints = self.X.shape[0]
        
        for i in range(no_of_datapoints):
            dist = distance(self.X[i], self.centers)
            cluster.append(np.argmax(dist))
        
        cluster = np.array(cluster)
        return cluster
        
    def resetCenter(self, cluster):
        centers = []
        
        for ik in range(self.k):
            new_center = self.X[cluster == ik].mean(axis = 0)
            centers.append(new_center)
        
        centers = np.array(centers)
        return centers
    
    def fit(self):
        for i in range(3):
            cluster = self.setCluster()
            centers = self.resetCenter(cluster)
            print(centers)
            print(self.centers)
            self.centers = centers
        

In [184]:
kmean = KMeans(img_flat, 5)

In [185]:
kmean.centers

array([[114.32681494, 194.0143805 , 252.8507754 ],
       [211.16600836, 118.19893583, 205.73252962],
       [116.10229501, 237.14448504, 169.12205049],
       [191.09384778, 221.32088171, 129.84681357],
       [ 30.24359505,   6.09674139, 231.92333335]])

In [186]:
cls = kmean.setCluster()

In [188]:
np.unique(cls)

array([0, 4], dtype=int64)

In [180]:
ctr = kmean.resetCenter(c)

C:\Users\Monika\AppData\Local\Temp\ipykernel_12516\1684440798.py:23: RuntimeWarning: Mean of empty slice.
  new_center = self.X[cluster == ik].mean(axis = 0)
C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\_methods.py:181: RuntimeWarning: invalid value encountered in true_divide
  ret = um.true_divide(


In [182]:
np.unique(cls == 2)

array([False])

In [167]:
ctr

array([[ 94.08169467,  52.03723033,  39.05105113],
       [177.17645567, 176.65615688, 178.06224934],
       [         nan,          nan,          nan],
       [         nan,          nan,          nan],
       [         nan,          nan,          nan]])