In [254]:
import gymnasium as gym
import random
import numpy as np
from collections import deque

from keras.models import Sequential
from keras.layers import Input, Dense, Dropout
from keras.optimizers import Adam

In [137]:
env = gym.make("CartPole-v1", render_mode="human")

In [112]:
env.reset()

(array([0.0335817 , 0.03408335, 0.04109202, 0.04026206], dtype=float32), {})

In [16]:
import matplotlib.pyplot as plt

In [57]:
%matplotlib inline

In [282]:
env1 = gym.make("CartPole-v1", render_mode="rgb_array")

for _ in range(1000):
    x = random.randint(0,1)
    env.step(x)
    print(env.observation_space.sample())
    env.render()
    
env.close()

[-8.4284134e-02  2.7582724e+38 -1.9479516e-01  1.2117571e+38]
[ 2.8465757e+00 -2.9862516e+38  9.9083886e-02 -1.3576616e+38]
[ 1.9267743e+00  1.2650294e+38  1.3027975e-01 -2.2406262e+38]
[ 1.4216582e+00  4.5983503e+37 -1.4024633e-01 -1.1595519e+38]
[-1.1986206e-01  1.9842911e+37  2.1126281e-01  2.4746460e+38]
[-2.7613413e+00  1.1029164e+38 -5.9075221e-02 -8.5262401e+35]
[-1.8936263e+00 -1.6822699e+38  1.2882628e-01  2.0255992e+38]
[ 1.4732327e+00  5.7897824e+36  2.8826189e-01 -1.6502284e+38]
[-3.9190264e+00  3.6105982e+36 -8.6041912e-03 -1.0123325e+38]
[-2.6133804e+00 -1.2549436e+38 -3.4662217e-01  3.3097388e+38]
[4.3703766e+00 6.8899178e+37 1.4303768e-01 4.2485797e+37]
[-1.4248923e+00 -1.5463852e+38  1.3525660e-01 -3.1442347e+38]
[ 2.0851710e+00 -1.3613485e+38 -2.0066452e-01 -2.0764166e+38]
[ 4.3181276e+00  5.0281402e+37  2.5298864e-02 -8.2719937e+37]
[-1.5103567e+00 -2.7951604e+38  1.3014236e-02  7.6583189e+37]
[-4.5427022e+00  1.5904090e+38 -3.7548450e-01  1.6134619e+38]
[-2.2256241e

Z:\Google\Anaconda\lib\site-packages\gymnasium\envs\classic_control\cartpole.py:177: UserWarning: WARN: You are calling 'step()' even though this environment has already returned terminated = True. You should always call 'reset()' once you receive 'terminated = True' -- any further steps are undefined behavior.
  logger.warn(


[-4.3190150e+00  2.3349692e+38 -3.5658625e-01 -8.5797757e+37]
[-3.1252727e-01  4.4350196e+37  3.0917659e-01 -1.7991065e+38]
[-2.2102301e+00 -2.3598946e+37  2.6056296e-01 -1.8657714e+38]
[ 2.5020456e-01 -1.7684951e+38 -3.5278428e-02  2.5962847e+38]
[ 4.2430410e+00 -1.5180770e+38 -7.8583859e-02 -1.0044369e+38]
[ 4.5362916e+00 -2.1364443e+37  1.7223699e-01  3.0600337e+38]
[-1.5939289e+00 -2.2697582e+38 -3.6694166e-01 -1.6879713e+38]
[ 4.7313356e+00  1.1705867e+38 -3.5756421e-01 -4.0730511e+37]
[-2.3070984e+00  2.8989344e+37  1.9465892e-01  9.7849676e+37]
[ 4.7663159e+00  3.2838308e+38 -2.0193161e-01  2.6668012e+38]
[ 4.2393866e+00  2.8249407e+38 -3.7348109e-01 -3.0286307e+38]
[ 2.3625992e-01 -1.8556634e+38  5.1569402e-02 -1.7494826e+38]
[-2.3212693e+00  2.1798597e+38 -6.4358763e-02 -3.3349311e+38]
[ 2.6562455e+00 -1.8753526e+38  2.4081266e-01  1.8787722e+38]
[-1.0603236e+00  4.9587976e+37 -2.2109650e-01 -1.7655868e+38]
[ 3.0431979e+00 -2.4367853e+38  3.7944755e-01  5.0846348e+37]
[-3.5406

[-3.2789915e+00  3.0225999e+38  1.4126605e-01 -1.7837836e+38]
[-3.1087639e+00  1.9489767e+38 -7.4553102e-02 -7.6793908e+37]
[ 1.6093462e+00  2.3890786e+38 -3.2849276e-01  3.0886329e+38]
[ 6.1565143e-01  2.1283077e+38 -2.9238785e-02 -2.0234525e+38]
[ 3.7565596e+00 -1.0171744e+38  1.5395778e-01  1.7531910e+38]
[-3.6743121e+00  5.0441186e+37 -2.5789249e-01 -3.1810065e+38]
[-1.2035259e+00  3.3352035e+38 -1.1211129e-01  2.6258948e+38]
[1.5962836e+00 1.5651047e+38 3.4580782e-01 2.7132329e+38]
[ 4.2513766e+00 -2.1870806e+38  3.5046965e-01  2.8644226e+38]
[-6.9199526e-01  2.3923283e+38 -2.6008609e-01  1.3751396e+38]
[-4.2847095e+00  2.5898986e+38  6.3755810e-02  1.7757408e+38]
[-1.4310802e+00  3.3973866e+38  1.7005612e-01 -2.3847205e+38]
[ 8.2725935e-02  2.5676723e+38  2.5044602e-01 -1.1187103e+37]
[ 4.4483671e+00  5.5123655e+37 -3.6744720e-01 -2.6962723e+38]
[-2.9659677e+00 -3.1036415e+38 -3.3844295e-01  1.6238720e+38]
[ 2.2105656e+00 -2.1798650e+38  4.3166324e-02 -1.5613363e+38]
[ 1.4624736e

[ 1.1750950e+00  2.9450742e+38 -2.6488721e-01  3.3069416e+38]
[ 1.1932376e-01  1.0959573e+38  2.5029073e-02 -8.3211704e+37]
[ 2.3555348e+00  1.7004191e+38 -2.3834834e-01  1.4412770e+38]
[-2.7241793e+00 -2.5677778e+38  1.1102391e-01 -2.3096497e+38]
[ 3.5721745e+00  6.6384149e+37 -3.0074298e-01 -1.6608548e+38]
[ 2.2539699e+00  3.1197822e+38 -3.6085147e-02 -3.0581371e+38]
[ 6.3579148e-01  1.9415458e+38  2.9871713e-03 -8.8541652e+37]
[ 1.3905827e+00  2.0870214e+38  2.8304836e-01 -1.5023164e+38]
[ 4.5742321e+00  1.4662434e+38 -3.4325963e-01 -1.1680382e+37]
[-1.7859836e+00 -2.8554578e+38 -3.4754287e-02  1.4581245e+38]
[-1.3049227e+00 -1.5858874e+38  2.3096015e-01 -1.4164449e+38]
[-4.1109195e+00  8.7003830e+37 -2.6760125e-01  1.7922089e+38]
[-2.7842612e+00  2.1789794e+38 -7.6658957e-02  3.2891965e+38]
[ 3.0121384e+00  5.5369746e+37  2.4164368e-01 -2.2678117e+38]
[4.5162959e+00 5.7016683e+37 2.6523226e-01 2.3457321e+38]
[-1.0816525e+00 -1.5434656e+38 -1.3387729e-01 -2.4084378e+38]
[-1.19591996

[ 1.02062136e-01 -1.14020243e+38  2.50197891e-02 -1.71136469e+37]
[-4.1915679e+00 -2.2696840e+37  3.3123764e-01 -2.6914125e+38]
[ 4.0996356e+00 -1.0845096e+38 -2.7205244e-01  1.9157856e+36]
[-2.2447059e+00  1.9099286e+38 -3.6708277e-02 -2.9566561e+38]
[ 2.2031653e+00  6.7604663e+37  1.7110042e-01 -1.4990693e+38]
[ 1.0851763e+00 -1.0260640e+38 -1.0153490e-01  2.3647777e+38]
[ 8.9078748e-01  2.0269983e+38 -1.4201103e-01  3.3991684e+38]
[ 3.8197734e+00  2.7750271e+38 -1.2750867e-01 -1.1295340e+37]
[-1.8229340e+00  2.0032552e+37 -4.0353745e-01  5.6938053e+37]
[ 2.8690660e+00  2.3595862e+38 -1.5372942e-01  3.1671916e+38]
[ 2.9957726e+00 -6.4550082e+37  3.1185147e-01  6.5735650e+37]
[ 1.9477353e+00  3.3501296e+38 -6.5238248e-03  2.0040149e+37]
[-9.8319691e-01  1.1530283e+38 -7.5049549e-02 -2.2361000e+38]
[ 4.1211057e+00  2.7550390e+38 -1.8500267e-01 -1.1757540e+38]
[-3.5949712e+00 -2.6866569e+37 -8.7705582e-02  3.1792444e+38]
[2.5928361e+00 2.8372783e+38 9.8852359e-02 1.7040922e+38]
[ 2.6448

[ 2.2937837e+00  1.8160971e+38 -1.6881771e-02  7.7214281e+37]
[ 6.6209441e-01 -5.3142139e+37  3.6037597e-01 -1.2351613e+37]
[-9.5658863e-01 -2.9943560e+38 -3.5675079e-01 -2.9153889e+38]
[-3.3017874e+00  5.6495998e+37 -6.0317650e-02 -1.7651542e+38]
[1.2957780e+00 1.3922058e+38 2.0452678e-01 2.7188580e+37]
[ 1.3773268e+00 -1.1472719e+38  3.5848287e-01  2.4786605e+38]
[ 3.9314382e+00  1.0975898e+38 -1.8119402e-01  1.7409617e+38]
[-2.9968967e+00 -1.3150011e+38  1.2640870e-01 -2.9192020e+38]
[2.9224350e+00 9.5638447e+37 2.1464648e-02 1.6553081e+38]
[ 1.1299002e+00  2.5615588e+38 -4.0695861e-01  2.2059090e+38]
[-1.5661758e+00  1.5594132e+38  3.8532493e-01 -2.6390017e+38]
[-3.0712416e+00 -9.2073530e+37 -3.1139481e-01 -1.5539508e+38]
[ 1.0527327e+00 -8.8241584e+37 -3.1155401e-01  2.8984935e+37]
[-3.6369103e-01 -2.2748962e+38  1.0762786e-01 -8.9542275e+37]
[2.8316722e+00 1.7408536e+38 3.8410589e-02 1.4513589e+38]
[-4.1715983e-01  1.4338751e+38 -3.7124607e-01  1.8902648e+38]
[-1.8150501e-01 -6.9

[4.4347482e+00 2.8812261e+37 1.2703666e-01 2.8057765e+38]
[2.6680748e+00 3.0428409e+38 3.8063085e-01 8.1963611e+37]
[ 1.7018492e+00  2.6630615e+38 -3.0440721e-01  1.7429530e+38]
[ 1.9515638e+00  7.8423422e+37  1.5991537e-01 -5.9808196e+37]
[-2.7289031e+00 -2.1702825e+38 -8.8345356e-02  3.1360420e+38]
[-2.3481174e+00  3.1315612e+37 -1.5504161e-01 -3.3317010e+38]
[ 5.2664280e-01 -1.8612437e+38 -1.6694097e-01 -4.3699542e+36]
[ 4.1955056e+00 -3.0588614e+38 -1.1254660e-01 -1.4192185e+38]
[ 3.4491930e+00  9.5446586e+37 -1.4829226e-01  1.8480950e+38]
[-4.3399531e-01  6.0194967e+37  3.3290276e-01 -8.2549600e+37]
[-1.0317163e+00  2.9410536e+38  1.6401063e-01  1.8742567e+38]
[1.6059662e+00 1.5630405e+38 6.6611622e-03 3.3539617e+38]
[-7.2176534e-01  6.8409713e+37  3.2573298e-01  4.7911514e+37]
[2.2319105e+00 2.1677488e+38 1.0103044e-01 1.9901991e+38]
[ 1.77468047e-01 -7.95978044e+37 -1.06849775e-01  2.45544611e+38]
[ 4.7183552e+00 -2.6455010e+38  1.0066021e-02 -2.9425405e+38]
[-2.7167332e-01 -7.7

[-4.0724444e+00  1.1172219e+38  1.5696880e-01  8.7126255e+37]
[-1.4544050e+00  2.1906587e+37 -3.4964612e-01 -9.5409063e+37]
[-3.3616599e-01  2.8737588e+37 -1.4311323e-01 -3.1057314e+38]
[ 2.3023835e-01  2.4626768e+38 -6.3499950e-02 -1.9508250e+38]
[ 4.4916549e-01 -2.3969439e+38  2.2140929e-01 -2.5016695e+38]
[-2.3151619e+00 -2.9077483e+38 -3.2467648e-01  2.7875992e+38]
[-9.1355771e-01  2.2863340e+38 -7.0568584e-02 -6.9241941e+37]
[-4.3227501e+00 -1.6374803e+38  1.7506890e-01 -2.2291056e+38]
[ 8.6584342e-01 -1.6416298e+38  1.5855172e-01 -2.2038878e+38]
[-1.9489843e+00  1.0931207e+38 -2.6293066e-01 -4.1441095e+37]
[ 1.8848498e+00  2.6385310e+38  1.8811080e-01 -3.8189937e+37]
[-1.8744303e-01 -2.0532139e+38 -1.6151035e-01 -1.5216922e+38]
[-3.1991539e+00 -3.2091960e+38 -1.4671013e-02  2.6886677e+38]
[ 2.6458631e+00  2.5229510e+38  4.2559464e-02 -8.1309429e+36]
[ 3.5298131e+00 -2.0612701e+38 -3.7279627e-01  2.5612769e+38]
[ 1.0819552e+00 -1.4016417e+38 -1.1807512e-01 -1.0550632e+38]
[-8.9604

In [138]:
for e in range(50): #epsiodes
    observation = env.reset()
    
    for t in range(100):
        action = env.action_space.sample() # random value in action spcae of the env
        observation, reward, done, info, _ = env.step(action)
        env.render()
        if done:
            print("Episode #{} of {}: score {}".format(e, 50, t))
            break
        
print("all episode done")
env.close()

Episode #0 of 50: score 21
Episode #1 of 50: score 49
Episode #2 of 50: score 18
Episode #3 of 50: score 15
Episode #4 of 50: score 32
Episode #5 of 50: score 17
Episode #6 of 50: score 10
Episode #7 of 50: score 12
Episode #8 of 50: score 22
Episode #9 of 50: score 64
Episode #10 of 50: score 51
Episode #11 of 50: score 36
Episode #12 of 50: score 19
Episode #13 of 50: score 26
Episode #14 of 50: score 18
Episode #15 of 50: score 14
Episode #16 of 50: score 12
Episode #17 of 50: score 30
Episode #18 of 50: score 15
Episode #19 of 50: score 13
Episode #20 of 50: score 20
Episode #21 of 50: score 21
Episode #22 of 50: score 27
Episode #23 of 50: score 12
Episode #24 of 50: score 18
Episode #25 of 50: score 12
Episode #26 of 50: score 27
Episode #27 of 50: score 11
Episode #28 of 50: score 45
Episode #29 of 50: score 10
Episode #30 of 50: score 36
Episode #31 of 50: score 14
Episode #32 of 50: score 9
Episode #33 of 50: score 14
Episode #34 of 50: score 11
Episode #35 of 50: score 13
Epi

In [141]:
env = gym.make("CartPole-v1", render_mode="human")
observation, info = env.reset(seed=42)
for _ in range(1000):
    action = env.action_space.sample()  # this is where you would insert your policy
    observation, reward, terminated, truncated, info = env.step(action)
    
    if terminated or truncated:
        observation, info = env.reset()
env.close()

`Exploration`: try out different/random things -> good in beginning.


`Exploitation`: sample/collect good experience from the past (exploration) -> good when you have explored a bit

In [308]:
class Agent:
    def __init__(self, state_size, action_size):
        self.state_size = state_size # state/observation size is the dimension in which the state of the agent can be represented
        self.action_size = action_size # different type of action/step we can take in the environment
        self.memory = deque(maxlen=2000) # this deque (doubly ended queue) will store the random + best actions agent performs
        self.gamma = 0.95 # discounted rate at which we penalize the later state rewards
        
        self.learning_rate = 1e-4
        self.epsilon = 1.0 # 100% random exploration
        self.epsilon_decay = 1e-2 # rate at which random exploration should decay/reduce
                                ## inversaly, rate at which we should start collec
        self.epsilon_min = 0.01
        self.model = self._create_model()
    
    def _create_model(self):
        model = Sequential()
        model.add(Input(4))
        model.add(Dense(24, activation='relu'))
        model.add(Dense(24, activation='relu'))
        model.add(Dense(2, activation='linear')) ## 2 is no of possible action
        model.compile(optimizer="adam", loss="mse")
        return model
        #model.summary()
        
    def store(self, state, action, reward, gameover, next_state):
        self.memory.append((state, action, reward, gameover, next_state))
    
    def action(self, state):
        
        # for epsilon % of time agent take random action 
        if np.random.rand() <= self.epsilon:
            return env.action_space.sample()
        
        # agent take action using neural netwok brain
        else:
            return np.argmax(self.model.predict(state)[0]) # argmax returns the action (index) of max target
    
    def train(self, batch_size=32):
        # training using "replay buffer" i.e., take a batch of data/experience from memory
        mini_batch = random.sample(self.memory, batch_size)
        
        for experience in mini_batch:
            state, action, reward, gameover, next_state = experience
            
            if not gameover:
                # game is not over - use bellman eqn to find approx target value of reward
                # print(self.model.predict(next_state)[0])
                target = reward + self.gamma * np.argmax(self.model.predict(next_state, verbose=0)[0])
            else:
                # when game is over
                target = reward
                
            #print(state)
            target_f = self.model.predict(state, verbose=0)
            # print(type(target_f), action, target, target_f)
            target_f[0, action] = target
            
            self.model.fit(state, target_f, epochs=1, verbose=0)
            
        if self.epsilon > self.epsilon_min:
            self.epsilon -= self.epsilon_decay
            
    def laod(self, name):
        self.load.weights_only(name)
        
    def save(self, name):
        self.model.save_weights(name)

`Play with environment and training our model`

In [163]:
n_episodes = 1_000
output_dir = "carpole_model/"

In [310]:
env = gym.make("CartPole-v1", render_mode="human")
x = env.reset()

In [306]:
# create a instance of agent 
state_size=4
action_size=2
agent = Agent(state_size, action_size)
done = False

In [ ]:
# let the agent play the game
for e in range(n_episodes):
    state = env.reset()[0]
    for time in range(500):
        act = agent.action(state) # agent deciding what button to press
        next_state, reward, gameover, truncated, info = env.step(act)
        # penalize reward when gameover
        if gameover: reward = -10
        # formatting next_state to store in agent memory as the NN (brain) can process np array
        state = state.reshape((1, state_size))
        next_state = next_state.reshape((1, state_size))
        # fed the agent brain with the data
        agent.store(state, action, reward, gameover, next_state)
        
        if gameover:
            print("Episode #{} of {} score: {} exploration rate: {:.2}".format(e, n_episodes, time, agent.epsilon))
            break
        
        if len(agent.memory) > 32:
            agent.train()
            
        if e%50 == 0:
            agent.save(output_dir+"weights_"+'%.4f' %e + ".hdf5")
        
print("model trained")

In [281]:
agent.memory[0] # state, action, reward, gameover, next_state

(array([[0.02175644, 0.04204665, 0.02615108, 0.0371155 ]], dtype=float32),
 0,
 array([[ 0.02259737, -0.15344036,  0.02689339,  0.3379333 ]],
       dtype=float32),
 1.0,
 False)

In [259]:
x = np.array([[-0.00822658, -0.01690743]])


In [286]:
print("<class 'numpy.ndarray'> 0 [[0.01952857 0.04128878 0.03365205 0.05385091]] [[-0.0052758   0.00259107]]")

<class 'numpy.ndarray'> 0 [[0.01952857 0.04128878 0.03365205 0.05385091]] [[-0.0052758   0.00259107]]
